# Generated by Django 2.2.4 on 2019-08-27 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        ('reportresponse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportresponse',
            name='report',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='report.Report'),
            preserve_default=False,
        ),
    ]
