# Generated by Django 2.2.4 on 2019-08-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportresponse', '0002_reportresponse_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportresponse',
            name='report',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.Report'),
        ),
    ]
