# Generated by Django 2.2.4 on 2019-08-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportresponse', '0004_reportresponse_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportresponse',
            old_name='user',
            new_name='author',
        ),
    ]
